replicaCount: 1

global:
  mcpAuthToken: ""

image:
  repository: nousresearch/hermes-agent
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

command: []

args:
  - gateway
  - run

hermesHome: /opt/data

profile:
  name: sre-agent
  install:
    enabled: true
    source: https://github.com/anthoai97/hermes-sre-profile.git
    path: profile
    alias: true
    setup: false
    extraArgs: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 9119
  targetPort: 9119
  annotations: {}

dashboard:
  enabled: true
  insecure: true

config:
  enabled: false
  fileName: config.yaml
  existingConfigMap: ""
  raw: ""
  data: {}

env:
  - name: KUBERNETES_MCP_URL
    value: http://mcp-server-kubernetes.hermes-sre.svc.cluster.local:3001/mcp

envFrom: []

persistence:
  enabled: true
  mountPath: /opt/data
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: ""
  existingClaim: ""
  annotations: {}

resources:
  limits:
    cpu: "2"
    memory: 4Gi
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
tolerations: []
affinity: {}

extraVolumes: []
extraVolumeMounts: []
